import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import './globals.css';
import '@mantine/core/styles.css';

import { MantineWrapper } from '@/utils/wrapper/MantineProvider';

const roboto = Roboto({
  weight: ['400', '500', '700', '300'],
  subsets: ['latin'],
  display: 'swap',
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <MantineWrapper>{children}</MantineWrapper>
      </body>
    </html>
  );
}
